# org: blueskybutterfly
app: patients-app
service: Patients

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'dev'}
  region: ${file(./config.json):REGION}
  profile: default
  environment:
    CLIENT_ID: ${file(./config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(./config.json):CLIENT_SECRET}
    REFRESH_TOKEN: ${file(./config.json):REFRESH_TOKEN}
    REGION: ${file(./config.json):REGION}
    AWS_KEY: ${file(./config.json):AWS_KEY}
    AWS_ID: ${file(./config.json):AWS_ID}

package:
  exclude:
    - node_modules/**
    - env/**
    - config.json


functions:
  handler:
    handler: handler.handler
    name: Patients
    description: DrChrono - import Patients every an hour
    timeout: 600
    reservedConcurrency: 1
    events:
      - schedule: rate(1 hour)

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters
  - serverless-prune-plugin
